# Shared supplicant scheduling; use one build-local source for all Wi-Fi APIs.
if(NOT TARGET idf::wpa_supplicant OR NOT CONFIG_ESP32_MQUICKJS_FEATURE_WIFI)
    return()
endif()
idf_component_get_property(_qjs_eloop_lib wpa_supplicant COMPONENT_LIB)
idf_component_get_property(_qjs_eloop_dir wpa_supplicant COMPONENT_DIR)
idf_build_get_property(_qjs_eloop_python PYTHON)
set(_qjs_eloop_script "${CMAKE_SOURCE_DIR}/scripts/sdk_patches/wpa/eloop.py")
set(_qjs_eloop_source "${_qjs_eloop_dir}/port/eloop.c")
set(_qjs_eloop_output "${CMAKE_BINARY_DIR}/esp32qjs_sdk_fixes/eloop.c")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${_qjs_eloop_script}" "${_qjs_eloop_source}")
execute_process(COMMAND "${_qjs_eloop_python}" "${CMAKE_SOURCE_DIR}/scripts/sdk_patch.py" eloop
    --source "${_qjs_eloop_source}" --output "${_qjs_eloop_output}"
    RESULT_VARIABLE _qjs_eloop_result ERROR_VARIABLE _qjs_eloop_error)
if(NOT _qjs_eloop_result EQUAL 0)
    message(FATAL_ERROR "ESP32QJS eloop fix failed: ${_qjs_eloop_error}")
endif()
get_target_property(_qjs_eloop_sources ${_qjs_eloop_lib} SOURCES)
set(_qjs_eloop_new_sources "")
set(_qjs_eloop_count 0)
foreach(_qjs_eloop_entry IN LISTS _qjs_eloop_sources)
    get_filename_component(_qjs_eloop_absolute "${_qjs_eloop_entry}" ABSOLUTE BASE_DIR "${_qjs_eloop_dir}")
    if(_qjs_eloop_absolute STREQUAL _qjs_eloop_source)
        list(APPEND _qjs_eloop_new_sources "${_qjs_eloop_output}")
        math(EXPR _qjs_eloop_count "${_qjs_eloop_count} + 1")
    else()
        list(APPEND _qjs_eloop_new_sources "${_qjs_eloop_entry}")
    endif()
endforeach()
if(NOT _qjs_eloop_count EQUAL 1)
    message(FATAL_ERROR "Expected exactly one SDK eloop.c, found ${_qjs_eloop_count}")
endif()
set_property(TARGET ${_qjs_eloop_lib} PROPERTY SOURCES "${_qjs_eloop_new_sources}")
