
#define CONFIG_SOC_WIFI_HE_SUPPORT 1
#define CONFIG_IDF_TARGET_ESP32C5 1
#define ESP_ERR_WIFI_TWT_FULL 0x3017
#define ESP_ERR_NOT_SUPPORTED 0x106
#define ESP_ERR_INVALID_RESPONSE 0x108
#define ESP_ERR_WIFI_NOT_ASSOC 0x3015
#define ESP_ERR_NOT_FINISHED 0x10c
typedef int JSValue;
typedef struct JSContext JSContext;
typedef struct { uint32_t prefix[4], timer_arg; } ETSTimer;
#define _Static_assert(...)
