#pragma once

/* Shared Raw TX limits/defaults. Keep these dependency-free so validators,
 * native queues and JS capture/capabilities consume exactly the same values.
 * These constants are not runtime configuration. */
#define ESP32_MQUICKJS_WIFI_RAW_TX_MIN_FRAME_BYTES 24U
#define ESP32_MQUICKJS_WIFI_RAW_TX_MAX_FRAME_BYTES 1500U
#define ESP32_MQUICKJS_WIFI_RAW_TX_QUEUE_MAX_PACKETS 128U
#define ESP32_MQUICKJS_WIFI_RAW_TX_QUEUE_MAX_FLUSHES 8U
#define ESP32_MQUICKJS_WIFI_RAW_TX_MAX_IN_FLIGHT 8U
#define ESP32_MQUICKJS_WIFI_RAW_TX_MAX_SESSIONS 8U
#define ESP32_MQUICKJS_WIFI_RAW_TX_MAX_RESULTS 8U
#define ESP32_MQUICKJS_WIFI_RAW_TX_MAX_PERIODIC_JOBS 8U
#define ESP32_MQUICKJS_WIFI_RAW_TX_LANE_CAPACITY 9U
#define ESP32_MQUICKJS_WIFI_RAW_TX_PERIODIC_MIN_INTERVAL_US 1000U

#define ESP32_MQUICKJS_WIFI_RAW_TX_DEFAULT_QUEUE_PACKETS 32U
#define ESP32_MQUICKJS_WIFI_RAW_TX_DEFAULT_MAX_IN_FLIGHT 1U
#define ESP32_MQUICKJS_WIFI_RAW_TX_DEFAULT_TIMEOUT_MS 1000U

/* Native scheduling delays; distinct from user deadlines and RF cadence. */
#define ESP32_MQUICKJS_WIFI_RAW_TX_SERVICE_RETRY_US 1000U
#define ESP32_MQUICKJS_WIFI_RAW_TX_CLEANUP_RETRY_US 100000U

/* CMake enables this only after validating the pinned SDK descriptor hooks. */
#ifndef ESP32_MQUICKJS_RAW_TX_DESCRIPTOR_IDENTITY
#define ESP32_MQUICKJS_RAW_TX_DESCRIPTOR_IDENTITY 0
#endif
#define ESP32_MQUICKJS_WIFI_RAW_TX_DRIVER_MAX_IN_FLIGHT \
    (ESP32_MQUICKJS_RAW_TX_DESCRIPTOR_IDENTITY ? \
     ESP32_MQUICKJS_WIFI_RAW_TX_MAX_IN_FLIGHT : ESP32_MQUICKJS_WIFI_RAW_TX_DEFAULT_MAX_IN_FLIGHT)
