#pragma once
/* The caller supplies sdkconfig.h, or equivalent host ROM build defines. */
#if CONFIG_ESP32_MQUICKJS_FEATURE_WIFI && CONFIG_SOC_WIFI_MESH_SUPPORT && CONFIG_ESP_WIFI_SOFTAP_SUPPORT && CONFIG_ESP_NETIF_USES_TCPIP_WITH_BSD_API && CONFIG_LWIP_IPV4 && !CONFIG_ESP_HOST_WIFI_ENABLED && (CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32C5 || CONFIG_IDF_TARGET_ESP32S3)
#define ESP32_MQUICKJS_WIFI_MESH_AVAILABLE 1
#endif
