#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "sdkconfig.h"
#include "esp_err.h"
#include "esp32_mquickjs.h"
#include "esp32_mquickjs_profile.h"

#define ESP32_MQUICKJS_MAX_TIMERS CONFIG_ESP32_MQUICKJS_MAX_TIMERS
#define ESP32_MQUICKJS_TIMER_QUEUE_LEN CONFIG_ESP32_MQUICKJS_TIMER_QUEUE_LEN
#define ESP32_MQUICKJS_MCU_NAME CONFIG_ESP32_MQUICKJS_MCU_NAME
#define ESP32_MQUICKJS_PSRAM_MODE CONFIG_ESP32_MQUICKJS_PSRAM_MODE
#define ESP32_MQUICKJS_WIFI_SSID_MAX_LEN 32
#define ESP32_MQUICKJS_WIFI_PASSWORD_MAX_LEN 64
#define ESP32_MQUICKJS_WIFI_IPV4_STR_LEN 16
#define ESP32_MQUICKJS_WIFI_HOSTNAME_MAX_LEN 64
#define ESP32_MQUICKJS_FS_STREAM_ID_KEY "__esp32qjsStreamId"
#define ESP32_MQUICKJS_FS_STREAM_GENERATION_KEY "__esp32qjsStreamGeneration"
#define ESP32_MQUICKJS_HEADERS_STORE_KEY "__esp32qjsHeadersStore"
#define JS_CLASS_HEADERS (JS_CLASS_USER + 0)
#define JS_CLASS_REQUEST (JS_CLASS_USER + 1)
#define JS_CLASS_RESPONSE (JS_CLASS_USER + 2)
#define JS_CLASS_STREAM (JS_CLASS_USER + 4)
#define JS_CLASS_HTTP_SERVER (JS_CLASS_USER + 5)
#define JS_CLASS_I2C_BUS (JS_CLASS_USER + 7)
#define JS_CLASS_SPI_BUS (JS_CLASS_USER + 8)
#define JS_CLASS_SPI_DEVICE (JS_CLASS_USER + 9)
#define JS_CLASS_UART_PORT (JS_CLASS_USER + 10)
#define JS_CLASS_BYTE_VIEW (JS_CLASS_USER + 11)
#define JS_CLASS_BYTE_SPAN_SOURCE (JS_CLASS_USER + 12)
#define JS_CLASS_BITMAP_SPAN_SOURCE (JS_CLASS_USER + 13)
#define JS_CLASS_BITMAP (JS_CLASS_USER + 14)
#define JS_CLASS_DISPLAY_FONT (JS_CLASS_USER + 15)
#define JS_CLASS_DISPLAY_COMMAND_BUFFER (JS_CLASS_USER + 16)
#define JS_CLASS_FUTURE (JS_CLASS_USER + 17)
#define JS_CLASS_EVENT_QUEUE (JS_CLASS_USER + 18)
#define JS_CLASS_I2S_CHANNEL (JS_CLASS_USER + 19)
#define JS_CLASS_CAMERA (JS_CLASS_USER + 20)
#define JS_CLASS_CAMERA_FRAME (JS_CLASS_USER + 21)
#define JS_CLASS_RMT_SYMBOL_BUFFER (JS_CLASS_USER + 22)
#define JS_CLASS_RMT_CHANNEL (JS_CLASS_USER + 23)
#define JS_CLASS_FS_VOLUME (JS_CLASS_USER + 24)
#define JS_CLASS_I2C_DEVICE (JS_CLASS_USER + 25)
#define JS_CLASS_TCP_SOCKET (JS_CLASS_USER + 26)
#define JS_CLASS_TCP_LISTENER (JS_CLASS_USER + 27)
#define JS_CLASS_UDP_SOCKET (JS_CLASS_USER + 28)
#define JS_CLASS_RPC_CODEC (JS_CLASS_USER + 29)
#define JS_CLASS_RPC_DECODER (JS_CLASS_USER + 30)
#define JS_CLASS_COUNT (JS_CLASS_USER + 31)

#if CONFIG_ESP32_MQUICKJS_FEATURE_FS
#define ESP32_MQUICKJS_MAX_SCRIPT_PATH CONFIG_ESP32_MQUICKJS_MAX_SCRIPT_PATH
#else
#define ESP32_MQUICKJS_MAX_SCRIPT_PATH 256
#endif

#if CONFIG_ESP32_MQUICKJS_FEATURE_GPIO
#define ESP32_MQUICKJS_USER_LED_PIN \
    esp32_mquickjs_profile_int_or("ESP32QJS_LED_PIN", CONFIG_ESP32_MQUICKJS_USER_LED_PIN)
#else
#define ESP32_MQUICKJS_USER_LED_PIN (-1)
#endif

#if CONFIG_ESP32_MQUICKJS_FEATURE_I2C
#define ESP32_MQUICKJS_I2C_DEFAULT_SDA_PIN \
    esp32_mquickjs_profile_int_or("ESP32QJS_I2C_SDA", CONFIG_ESP32_MQUICKJS_I2C_DEFAULT_SDA_PIN)
#define ESP32_MQUICKJS_I2C_DEFAULT_SCL_PIN \
    esp32_mquickjs_profile_int_or("ESP32QJS_I2C_SCL", CONFIG_ESP32_MQUICKJS_I2C_DEFAULT_SCL_PIN)
#define ESP32_MQUICKJS_I2C_DEFAULT_FREQ_HZ \
    esp32_mquickjs_profile_uint_or("ESP32QJS_I2C_FREQ_HZ", (uint32_t)CONFIG_ESP32_MQUICKJS_I2C_DEFAULT_FREQ_HZ)
#define ESP32_MQUICKJS_I2C_DEFAULT_TIMEOUT_MS \
    esp32_mquickjs_profile_uint_or("ESP32QJS_I2C_TIMEOUT_MS", (uint32_t)CONFIG_ESP32_MQUICKJS_I2C_DEFAULT_TIMEOUT_MS)
#else
#define ESP32_MQUICKJS_I2C_DEFAULT_SDA_PIN 5
#define ESP32_MQUICKJS_I2C_DEFAULT_SCL_PIN 6
#define ESP32_MQUICKJS_I2C_DEFAULT_FREQ_HZ ((uint32_t)400000U)
#define ESP32_MQUICKJS_I2C_DEFAULT_TIMEOUT_MS ((uint32_t)100U)
#endif

#if CONFIG_ESP32_MQUICKJS_FEATURE_SPI
#define ESP32_MQUICKJS_SPI_DEFAULT_SCLK_PIN \
    esp32_mquickjs_profile_int_or("ESP32QJS_SPI_SCLK", CONFIG_ESP32_MQUICKJS_SPI_DEFAULT_SCLK_PIN)
#define ESP32_MQUICKJS_SPI_DEFAULT_MOSI_PIN \
    esp32_mquickjs_profile_int_or("ESP32QJS_SPI_MOSI", CONFIG_ESP32_MQUICKJS_SPI_DEFAULT_MOSI_PIN)
#define ESP32_MQUICKJS_SPI_DEFAULT_MISO_PIN \
    esp32_mquickjs_profile_int_or("ESP32QJS_SPI_MISO", CONFIG_ESP32_MQUICKJS_SPI_DEFAULT_MISO_PIN)
#define ESP32_MQUICKJS_SPI_DEFAULT_CS_PIN \
    esp32_mquickjs_profile_int_or("ESP32QJS_SPI_CS", CONFIG_ESP32_MQUICKJS_SPI_DEFAULT_CS_PIN)
#define ESP32_MQUICKJS_SPI_DEFAULT_FREQ_HZ \
    esp32_mquickjs_profile_uint_or("ESP32QJS_SPI_FREQ_HZ", (uint32_t)CONFIG_ESP32_MQUICKJS_SPI_DEFAULT_FREQ_HZ)
#define ESP32_MQUICKJS_SPI_DEFAULT_QUEUE_SIZE \
    esp32_mquickjs_profile_uint_or("ESP32QJS_SPI_QUEUE_SIZE", (uint32_t)CONFIG_ESP32_MQUICKJS_SPI_DEFAULT_QUEUE_SIZE)
#define ESP32_MQUICKJS_SPI_DEFAULT_MAX_TRANSFER_SIZE \
    esp32_mquickjs_profile_uint_or("ESP32QJS_SPI_MAX_TRANSFER_SIZE", (uint32_t)CONFIG_ESP32_MQUICKJS_SPI_DEFAULT_MAX_TRANSFER_SIZE)
#define ESP32_MQUICKJS_SPI_MAX_DEVICES_PER_BUS CONFIG_ESP32_MQUICKJS_SPI_MAX_DEVICES_PER_BUS
#else
#define ESP32_MQUICKJS_SPI_DEFAULT_SCLK_PIN 18
#define ESP32_MQUICKJS_SPI_DEFAULT_MOSI_PIN 23
#define ESP32_MQUICKJS_SPI_DEFAULT_MISO_PIN 19
#define ESP32_MQUICKJS_SPI_DEFAULT_CS_PIN (-1)
#define ESP32_MQUICKJS_SPI_DEFAULT_FREQ_HZ ((uint32_t)1000000U)
#define ESP32_MQUICKJS_SPI_DEFAULT_QUEUE_SIZE ((uint32_t)1U)
#define ESP32_MQUICKJS_SPI_DEFAULT_MAX_TRANSFER_SIZE ((uint32_t)4092U)
#define ESP32_MQUICKJS_SPI_MAX_DEVICES_PER_BUS 4
#endif

#if CONFIG_ESP32_MQUICKJS_FEATURE_UART
#define ESP32_MQUICKJS_UART_DEFAULT_PORT \
    esp32_mquickjs_profile_int_or("ESP32QJS_UART_PORT", CONFIG_ESP32_MQUICKJS_UART_DEFAULT_PORT)
#define ESP32_MQUICKJS_UART_DEFAULT_TX_PIN \
    esp32_mquickjs_profile_int_or("ESP32QJS_UART_TX", CONFIG_ESP32_MQUICKJS_UART_DEFAULT_TX_PIN)
#define ESP32_MQUICKJS_UART_DEFAULT_RX_PIN \
    esp32_mquickjs_profile_int_or("ESP32QJS_UART_RX", CONFIG_ESP32_MQUICKJS_UART_DEFAULT_RX_PIN)
#define ESP32_MQUICKJS_UART_DEFAULT_BAUD \
    esp32_mquickjs_profile_uint_or("ESP32QJS_UART_BAUD", (uint32_t)CONFIG_ESP32_MQUICKJS_UART_DEFAULT_BAUD)
#define ESP32_MQUICKJS_UART_DEFAULT_RX_BUFFER_SIZE \
    esp32_mquickjs_profile_uint_or("ESP32QJS_UART_RX_BUFFER_SIZE", (uint32_t)CONFIG_ESP32_MQUICKJS_UART_DEFAULT_RX_BUFFER_SIZE)
#define ESP32_MQUICKJS_UART_DEFAULT_TX_BUFFER_SIZE \
    esp32_mquickjs_profile_uint_or("ESP32QJS_UART_TX_BUFFER_SIZE", (uint32_t)CONFIG_ESP32_MQUICKJS_UART_DEFAULT_TX_BUFFER_SIZE)
#define ESP32_MQUICKJS_UART_DEFAULT_TIMEOUT_MS \
    esp32_mquickjs_profile_uint_or("ESP32QJS_UART_TIMEOUT_MS", (uint32_t)CONFIG_ESP32_MQUICKJS_UART_DEFAULT_TIMEOUT_MS)
#else
#define ESP32_MQUICKJS_UART_DEFAULT_PORT 1
#define ESP32_MQUICKJS_UART_DEFAULT_TX_PIN (-1)
#define ESP32_MQUICKJS_UART_DEFAULT_RX_PIN (-1)
#define ESP32_MQUICKJS_UART_DEFAULT_BAUD ((uint32_t)115200U)
#define ESP32_MQUICKJS_UART_DEFAULT_RX_BUFFER_SIZE ((uint32_t)1024U)
#define ESP32_MQUICKJS_UART_DEFAULT_TX_BUFFER_SIZE ((uint32_t)1024U)
#define ESP32_MQUICKJS_UART_DEFAULT_TIMEOUT_MS ((uint32_t)100U)
#endif

#if CONFIG_ESP32_MQUICKJS_FEATURE_WIFI
#define ESP32_MQUICKJS_WIFI_DEFAULT_TIMEOUT_MS ((uint32_t)CONFIG_ESP32_MQUICKJS_WIFI_DEFAULT_TIMEOUT_MS)
#else
#define ESP32_MQUICKJS_WIFI_DEFAULT_TIMEOUT_MS ((uint32_t)15000U)
#endif

#if CONFIG_ESP32_MQUICKJS_FEATURE_HTTP
#define ESP32_MQUICKJS_HTTP_DEFAULT_TIMEOUT_MS ((uint32_t)CONFIG_ESP32_MQUICKJS_HTTP_DEFAULT_TIMEOUT_MS)
#define ESP32_MQUICKJS_HTTP_TASK_STACK_SIZE CONFIG_ESP32_MQUICKJS_HTTP_TASK_STACK_SIZE
#else
#define ESP32_MQUICKJS_HTTP_DEFAULT_TIMEOUT_MS ((uint32_t)15000U)
#define ESP32_MQUICKJS_HTTP_TASK_STACK_SIZE 8192
#endif

#ifdef CONFIG_ESP32_MQUICKJS_USER_LED_ACTIVE_LOW
#define ESP32_MQUICKJS_USER_LED_ACTIVE_LOW \
    esp32_mquickjs_profile_bool_or("ESP32QJS_LED_ACTIVE_LOW", true)
#else
#define ESP32_MQUICKJS_USER_LED_ACTIVE_LOW \
    esp32_mquickjs_profile_bool_or("ESP32QJS_LED_ACTIVE_LOW", false)
#endif

#ifdef CONFIG_ESP32_MQUICKJS_I2C_ENABLE_INTERNAL_PULLUP
#define ESP32_MQUICKJS_I2C_ENABLE_INTERNAL_PULLUP \
    esp32_mquickjs_profile_bool_or("ESP32QJS_I2C_INTERNAL_PULLUP", true)
#else
#define ESP32_MQUICKJS_I2C_ENABLE_INTERNAL_PULLUP \
    esp32_mquickjs_profile_bool_or("ESP32QJS_I2C_INTERNAL_PULLUP", false)
#endif

typedef struct {
    bool initialized;
    bool started;
    bool connected;
    bool scanning;
    char ssid[ESP32_MQUICKJS_WIFI_SSID_MAX_LEN + 1];
    char hostname[ESP32_MQUICKJS_WIFI_HOSTNAME_MAX_LEN + 1];
    char ip[ESP32_MQUICKJS_WIFI_IPV4_STR_LEN];
    char netmask[ESP32_MQUICKJS_WIFI_IPV4_STR_LEN];
    char gateway[ESP32_MQUICKJS_WIFI_IPV4_STR_LEN];
    int32_t last_disconnect_reason;
} esp32_mquickjs_wifi_status_t;

typedef struct {
    int32_t stream_id;
    uint32_t generation;
} esp32_mquickjs_fs_stream_ref_t;
