# Keep reviewed shared-PHY GPIO corrections inside the immutable build copy.
if(NOT CONFIG_ESP32_MQUICKJS_FEATURE_WIFI OR CONFIG_ESP_HOST_WIFI_ENABLED OR
   NOT IDF_TARGET MATCHES "^esp32(c3|c5|s3)$")
    return()
endif()
idf_component_get_property(_ant_dir esp_phy COMPONENT_DIR)
idf_component_get_property(_ant_lib esp_phy COMPONENT_LIB)
idf_build_get_property(_ant_python PYTHON)
idf_component_get_property(_ant_hw_dir esp_hw_support COMPONENT_DIR)
file(SHA256 "${_ant_dir}/include/esp_phy.h" _ant_header_hash)
file(SHA256 "${_ant_hw_dir}/include/esp_private/esp_gpio_reserve.h" _ant_reserve_hash)
if(NOT _ant_header_hash STREQUAL "fe37b3a34e67a52405f146d358e57f51b91303233ab3676889ec94854daef682" OR
   NOT _ant_reserve_hash STREQUAL "df9443201d24f4007736d22b4aaae3246537c0267621d87ceb35e723fc5c545e")
    message(FATAL_ERROR "Unreviewed antenna/GPIO reserve ABI")
endif()
set(_ant_script "${CMAKE_CURRENT_LIST_DIR}/patch_idf_phy_antenna.py")
set(_ant_source "${_ant_dir}/src/phy_common.c")
set(_ant_output "${CMAKE_BINARY_DIR}/esp32qjs_sdk_fixes/phy/phy_common.c")
set(_ant_init_source "${_ant_dir}/src/phy_init.c")
set(_ant_init_output "${CMAKE_BINARY_DIR}/esp32qjs_sdk_fixes/phy/phy_init.c")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_ant_script}" "${_ant_source}"
    "${_ant_init_source}" "${_ant_dir}/include/esp_phy.h" "${_ant_hw_dir}/include/esp_private/esp_gpio_reserve.h")
execute_process(COMMAND "${_ant_python}" "${_ant_script}" --source "${_ant_source}" --output "${_ant_output}"
    --phy-init "${_ant_init_source}" --init-output "${_ant_init_output}"
    RESULT_VARIABLE _ant_result OUTPUT_VARIABLE _ant_message ERROR_VARIABLE _ant_error)
if(NOT _ant_result EQUAL 0)
    message(FATAL_ERROR "ESP32QJS antenna GPIO fix failed: ${_ant_error}")
endif()
get_target_property(_ant_sources ${_ant_lib} SOURCES)
set(_ant_new_sources "")
set(_ant_count 0)
foreach(_ant_source_entry IN LISTS _ant_sources)
    get_filename_component(_ant_absolute "${_ant_source_entry}" ABSOLUTE BASE_DIR "${_ant_dir}")
    if(_ant_absolute STREQUAL "${_ant_source}")
        list(APPEND _ant_new_sources "${_ant_output}")
        math(EXPR _ant_count "${_ant_count} + 1")
    elseif(_ant_absolute STREQUAL "${_ant_init_source}")
        list(APPEND _ant_new_sources "${_ant_init_output}")
        math(EXPR _ant_count "${_ant_count} + 1")
    else()
        list(APPEND _ant_new_sources "${_ant_source_entry}")
    endif()
endforeach()
if(NOT _ant_count EQUAL 2)
    message(FATAL_ERROR "Expected exactly one native phy_common.c and phy_init.c source")
endif()
set_property(TARGET ${_ant_lib} PROPERTY SOURCES "${_ant_new_sources}")
